# Generated by Django 3.0.4 on 2020-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20200315_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
