# Generated by Django 3.0.4 on 2020-03-16 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_auto_20200315_1940'),
        ('business', '0005_auto_20200316_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivers_to',
            field=models.ManyToManyField(related_name='delivers', to='geodata.NPA'),
        ),
        migrations.AddField(
            model_name='business',
            name='other_categories',
            field=models.ManyToManyField(related_name='as_other_category', to='business.Category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located', to='geodata.NPA'),
        ),
        migrations.AlterField(
            model_name='business',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_main_category', to='business.Category'),
        ),
    ]
