# Generated by Django 3.0.4 on 2020-03-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_auto_20200315_1940'),
        ('business', '0006_auto_20200316_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='delivers_to',
            field=models.ManyToManyField(blank=True, related_name='delivers', to='geodata.NPA'),
        ),
        migrations.AlterField(
            model_name='business',
            name='other_categories',
            field=models.ManyToManyField(blank=True, related_name='as_other_category', to='business.Category'),
        ),
    ]
