# Generated by Django 3.0.4 on 2020-03-16 12:12

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20200316_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
