# Generated by Django 3.0.4 on 2020-03-16 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
