# Generated by Django 3.0.4 on 2020-03-16 16:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0008_auto_20200315_1940'),
        ('business', '0012_auto_20200316_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='data',
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='delivery',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_request', to='geodata.NPA'),
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='request',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
