# Generated by Django 3.0.4 on 2020-03-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_auto_20200316_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='website',
            field=models.URLField(),
        ),
    ]
