# Generated by Django 3.0.4 on 2020-03-21 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20200319_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='id',
        ),
        migrations.AddField(
            model_name='request',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Manual'), (1, 'Web form'), (2, 'API')], default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='source_uuid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='request',
            name='ttl',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='delivery',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
