# Generated by Django 3.0.4 on 2020-03-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20200321_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='checksum',
            field=models.CharField(default='xxx', max_length=255),
            preserve_default=False,
        ),
    ]
