# Generated by Django 3.0.4 on 2020-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_request_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
