# Generated by Django 3.0.4 on 2020-03-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0011_auto_20200319_1713'),
        ('business', '0018_auto_20200322_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='located_request', to='geodata.NPA'),
        ),
    ]
