# Generated by Django 3.0.4 on 2020-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0011_auto_20200319_1713'),
        ('business', '0020_auto_20200322_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivers_to_canton',
            field=models.ManyToManyField(blank=True, related_name='delivers', to='geodata.Canton'),
        ),
        migrations.AddField(
            model_name='business',
            name='delivers_to_district',
            field=models.ManyToManyField(blank=True, related_name='delivers', to='geodata.District'),
        ),
        migrations.AddField(
            model_name='business',
            name='delivers_to_municipality',
            field=models.ManyToManyField(blank=True, related_name='delivers', to='geodata.Municipality'),
        ),
    ]
