# Generated by Django 3.0.4 on 2020-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_auto_20200323_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
