# Generated by Django 3.0.4 on 2020-03-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_business_delivers_to_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='delivers_to_ch',
            field=models.BooleanField(default=False, verbose_name='Delivers to whole Switzerland'),
        ),
    ]
