# Generated by Django 3.0.4 on 2020-03-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
