# Generated by Django 3.0.4 on 2020-03-26 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


state_request = {}
state_business = {}


def collect_state(apps, schema_editor):

        db_alias = schema_editor.connection.alias
        
        # Requests
        Request = apps.get_model('business', 'Request')
        reqs = Request.objects.using(db_alias).all()
        for req in reqs:
            if req.deleted:
                state_request[req.pk] = 5
            elif req.handled:
                state_request[req.pk] = 3
            else:
                state_request[req.pk] = 1
        
        # Businesses
        Business = apps.get_model('business', 'Business')
        buss = Business.objects.using(db_alias).all()
        for bus in buss:
            if bus.deleted:
                state_business[bus.pk] = 2
            else:
                state_business[bus.pk] = 1


def set_state(apps, schema_editor):

        db_alias = schema_editor.connection.alias
        
        # Requests
        RequestHistoryEvent = apps.get_model('business', 'RequestHistoryEvent')
        Request = apps.get_model('business', 'Request')
        for pk, state in state_request.items():
            event = RequestHistoryEvent(
                parent=Request.objects.using(db_alias).get(pk=pk),
                old_status=0,
                new_status=state,
            )
            event.save()
        
        # Businesses
        BusinessHistoryEvent = apps.get_model('business', 'BusinessHistoryEvent')
        Business = apps.get_model('business', 'Business')
        for pk, state in state_business.items():
            event = BusinessHistoryEvent(
                parent=Business.objects.using(db_alias).get(pk=pk),
                old_status=0,
                new_status=state
            )
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0028_auto_20200325_1054'),
    ]

    operations = [
        migrations.RunPython(collect_state),
        migrations.RemoveField(
            model_name='business',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='request',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='request',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='request',
            name='handled',
        ),
        migrations.RemoveField(
            model_name='request',
            name='update',
        ),
        migrations.CreateModel(
            name='RequestHistoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.PositiveSmallIntegerField(choices=[(0, 'Void'), (1, 'New'), (2, 'In process'), (3, 'Handled'), (4, 'Updated'), (5, 'Deleted'), (6, 'Keepalive')])),
                ('new_status', models.PositiveSmallIntegerField(choices=[(0, 'Void'), (1, 'New'), (2, 'In process'), (3, 'Handled'), (4, 'Updated'), (5, 'Deleted'), (6, 'Keepalive')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Request')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessHistoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.PositiveSmallIntegerField(choices=[(0, 'Void'), (1, 'Valid'), (2, 'Deleted')])),
                ('new_status', models.PositiveSmallIntegerField(choices=[(0, 'Void'), (1, 'Valid'), (2, 'Deleted')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(set_state),
    ]
