# Generated by Django 3.0.4 on 2020-03-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20200326_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshistoryevent',
            name='new_status',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='businesshistoryevent',
            name='old_status',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='requesthistoryevent',
            name='new_status',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='requesthistoryevent',
            name='old_status',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
