# Generated by Django 3.0.4 on 2020-03-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20200326_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
