# Generated by Django 3.0.4 on 2020-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_request_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian')], default='en', max_length=2),
        ),
    ]
