# Generated by Django 3.0.4 on 2020-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_auto_20200326_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='contact',
            field=models.TextField(blank=True),
        ),
    ]
