# Generated by Django 3.0.4 on 2020-03-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_auto_20200326_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshistoryevent',
            name='event_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businesshistoryevent',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'Status update'), (2, 'API keepalive')], default=0),
        ),
        migrations.AddField(
            model_name='requesthistoryevent',
            name='event_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requesthistoryevent',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'Status update'), (2, 'API keepalive')], default=0),
        ),
    ]
