# Generated by Django 3.0.4 on 2020-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_auto_20200326_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshistoryevent',
            name='event_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='requesthistoryevent',
            name='event_data',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
