# Generated by Django 3.0.4 on 2020-04-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20200328_1636'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businesshistoryevent',
            index=models.Index(fields=['parent', '-time', 'new_status'], name='business_bu_parent__879b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshistoryevent',
            index=models.Index(fields=['parent', 'event_type', '-time', 'new_status'], name='business_bu_parent__ab97e2_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistoryevent',
            index=models.Index(fields=['parent', '-time', 'new_status'], name='business_re_parent__de5625_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistoryevent',
            index=models.Index(fields=['parent', 'event_type', '-time', 'new_status'], name='business_re_parent__512358_idx'),
        ),
    ]
