# Generated by Django 3.0.4 on 2020-04-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_auto_20200407_2349'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businesshistoryevent',
            index=models.Index(fields=['parent', '-time'], name='business_bu_parent__90f929_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshistoryevent',
            index=models.Index(fields=['parent', 'event_type', '-time'], name='business_bu_parent__dc9a61_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistoryevent',
            index=models.Index(fields=['parent', '-time'], name='business_re_parent__b766f6_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistoryevent',
            index=models.Index(fields=['parent', 'event_type', '-time'], name='business_re_parent__ed75e7_idx'),
        ),
    ]
