# Generated by Django 3.0.4 on 2020-04-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20200407_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_businesses', to='business.Request'),
        ),
    ]
