# Generated by Django 3.0.4 on 2020-04-09 17:03

import uuid

from django.db import migrations, models


def fill_source_uuid(apps, schema_editor):

    Request = apps.get_model("business", "Request")
    db_alias = schema_editor.connection.alias
    
    requests = Request.objects.filter(source_uuid='')
    for request in requests:
        request.source_uuid = str(uuid.uuid4())
        request.save()


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_auto_20200408_2248'),
    ]

    operations = [
        migrations.RunPython(fill_source_uuid),
        migrations.AlterField(
            model_name='request',
            name='source_uuid',
            field=models.CharField(blank=False, max_length=255, unique=True),
        ),
    ]
