# Generated by Django 3.0.4 on 2020-03-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofs_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('canton', models.CharField(max_length=2)),
                ('aglo_id', models.PositiveIntegerField()),
            ],
        ),
    ]
