# Generated by Django 3.0.4 on 2020-03-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='aglo_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
