# Generated by Django 3.0.4 on 2020-03-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20200315_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'municipalities'},
        ),
        migrations.CreateModel(
            name='NPA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onrp', models.PositiveIntegerField(unique=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Municipality')),
            ],
        ),
    ]
