# Generated by Django 3.0.4 on 2020-03-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0004_auto_20200315_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npa',
            old_name='onrp',
            new_name='onrp_id',
        ),
    ]
