# Generated by Django 3.0.4 on 2020-03-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0005_auto_20200315_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='npa',
            name='npa',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
