# Generated by Django 3.0.4 on 2020-03-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0007_npa_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npa',
            options={'verbose_name': 'NPA', 'verbose_name_plural': 'NPAs'},
        ),
    ]
