# Generated by Django 3.0.4 on 2020-03-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0009_auto_20200319_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofs_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_de', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('name_it', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ofs_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_de', models.CharField(max_length=100, null=True)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('name_it', models.CharField(max_length=100, null=True)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geodata.Canton')),
            ],
        ),
        migrations.AddField(
            model_name='municipality',
            name='canton_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.Canton'),
        ),
    ]
