# Generated by Django 3.0.4 on 2020-03-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0010_auto_20200319_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='canton_id',
        ),
        migrations.AddField(
            model_name='municipality',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodata.District'),
        ),
    ]
