# Generated by Django 3.0.4 on 2020-04-03 17:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0011_auto_20200319_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='npa',
            name='geo_center',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='npa',
            name='geo_e',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='npa',
            name='geo_n',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='npa',
            name='lang',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'German'), (2, 'French'), (3, 'Italian'), (4, 'Romansh')], default=0),
        ),
    ]
