# Generated by Django 3.0.4 on 2020-04-03 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point


def add_default_data(apps, schema_editor):

    NPA = apps.get_model('geodata', 'NPA')
    for npa in NPA.objects.all():
        npa.geo_center = Point(8.226667, 46.801111)
        npa.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0012_auto_20200403_1955'),
    ]

    operations = [
        migrations.RunPython(add_default_data)
    ]
