# Generated by Django 3.0.4 on 2020-04-03 18:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0013_auto_20200403_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npa',
            name='geo_center',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.RunSQL("create spatial index sp_index on geodata_npa(geo_center);")
    ]
