stayhome:
  sync-service-url: 'http://localhost:8080'
  run-on-start: true
  integrations:
    localhero:
      scrape-cron: '* * */6 * * *'
      target-url: ${stayhome.sync-service-url}
      chunk-size: 50
      page-size: 50
      parallel-threads: 2
      request-ttl: 3d
      sources:
        - key: 'bern'
          providerName: 'bern-local-hero'
          url: 'https://bern.local-hero.ch'
          place: 'Bern'
        - key: 'winterthur'
          providerName: 'winterhur-local-hero'
          url: 'https://winterthur.local-hero.ch'
          place: 'Winterthur'

spring:
  batch:
    job:
      enabled: ${stayhome.run-on-start}

logging:
  level:
    ROOT: INFO
