stayhome:
  integrations:
    localhero:
      scrape-cron: '* */5 * * * *'
      source-urls:
        - 'http://localhost:3001'
      target-url: 'http://localhost:8080'
      chunk-size: 10
      ttl-seconds: 1000

spring:
  batch:
    job:
      enabled: true

logging:
  level:
    org.springframework.scheduling: 'DEBUG'
