stayhome:
  integrations:
    localhero:
      scrape-cron: '* */5 * * * *'
      source-urls:
        - 'http://localhost:3001/bern'
        - 'http://localhost:3001/winterthur'
      target-url: 'http://localhost:8080'

spring:
  batch:
    job:
      enabled: true

