stayhome:
  sync-service-url: 'http://localhost:8080'
  run-on-start: true
  integrations:
    localhero:
      scrape-cron: '-'

     # source-urls:
        #   - 'http://localhost:3001/bern'
      # - 'http://localhost:3001/winterthur'
